# Generated by Django 2.2.3 on 2019-07-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0019_auto_20190704_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
