# Generated by Django 2.0.2 on 2019-06-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can view dashboard', 'To open dashboard'), ('can view manager level', 'To open manager dashboard'))},
        ),
    ]
